name: Deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install dependencies
        run: npm ci

      - name: Build with vite
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Install Site SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: site-key
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          config: |
            Host connerowen-site
              HostName 164.92.88.111
              User conner
              IdentityFile ~/.ssh/site-key

      - name: Delete Existing Dist
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 164.92.88.111
          username: conner
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/home
            sudo rm -Rf *

      - name: Copy New Dist Folder
        run: scp -r dist/ connerowen-site:/home/conner/shotskydiver.github.io/

      - name: Move Dist & NPM Install
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 164.92.88.111
          username: conner
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd shotskydiver.github.io
            sudo cp -R dist/* /var/www/home
            git fetch
            git pull
            sudo systemctl restart nginx

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
